version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
  dnd-app:
    build: ./dnd-app
    container_name: dnd-app
    env_file:
      - ./dnd-app/development.env
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - redis
      - mongo
  dnd-app-frontend:
    build: ./dnd-app-frontend
    container_name: dnd-app-frontend
    env_file:
      - ./dnd-app-frontend/development.env
    ports:
      - '8080:8080'
    depends_on:
      - dnd-app
  dnd-app-db-init:
    build: ./dnd-app-db-init
    container_name: dnd-app-db-init
    environment:
      WAIT_HOSTS: dnd-app:3000
    depends_on:
      - dnd-app
      - mongo