version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
  dnd-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file:
      - development.env
    volumes:
      - ./.db-data:/data/db
      - ./:/dnd-app
    depends_on:
      - redis
      - mongo
